In [2]:
# Numpyのアレイを利用
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array = np.array(my_list1)

In [5]:
my_array

array([1, 2, 3, 4])

In [6]:
my_list1

[1, 2, 3, 4]

In [7]:
my_list2 = [11,22,33,44]

In [8]:
my_list1 + my_list2

[1, 2, 3, 4, 11, 22, 33, 44]

In [9]:
my_array2 = np.array(my_list2)

In [10]:
my_array2

array([11, 22, 33, 44])

In [11]:
my_array + my_array2

array([12, 24, 36, 48])

In [12]:
my_list1,my_array2

([1, 2, 3, 4], array([11, 22, 33, 44]))

In [13]:
my_lists = [my_array, my_array2]

In [14]:
my_lists

[array([1, 2, 3, 4]), array([11, 22, 33, 44])]

In [15]:
my_lists = [my_list1, my_list2]

In [16]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [18]:
my_array3 = np.array(my_lists)

In [19]:
my_array3

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [21]:
my_array3.shape

(2, 4)

In [22]:
my_array3.dtype

dtype('int32')